spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: ALWAYS
      platform: postgresql
    job:
      enabled: true
  cloud:
    aws:
      region:
        static: us-east-1  # Set your AWS region here
      credentials:
        access-key: test
        secret-key: test
      sqs:
        enabled: true
        endpoint: http://localhost:4566
server:
  port: 9090
